CREATE TABLE ATOR (

   ID_ATOR VARCHAR(20 BYTE) NOT NULL,
   NOME_ATOR VARCHAR (40 byte),
   NACIONALIDADE VARCHAR (20 BYTES),
   IDADE INTEGER,

   CONSTRAINT ATOR_pk PRIMARY KEY (ID_ATOR),
);
commit;

CREATE TABLE FILME(
	ID_FILME VARCHAR(20 BYTE),
	NOME_FILME VARCHAR(40 BYTE),
	DIRETOR_ID VARCHAR(20 BYTE),
    
    CONSTRAINT FILME_pk PRIMARY KEY (ID_FILME),
	CONSTRAINT FILME_fk FOREIGN KEY (DIRETOR_ID) REFERENCES DIRETOR(ID_DIRETOR),

);
commit;

CREATE TABLE PARTICIPA(
	COD_ATOR VARCHAR(20 BYTE),
	COD_FILME VARCHAR(20 BYTE),
    
    CONSTRAINT PARTICIPA_pk1 PRIMARY KEY (COD_ATOR),
    CONSTRAINT PARTICIPA_pk2 PRIMARY KEY (COD_FILME),
    CONSTRAINT PARTICIPA_fk1 FOREIGN KEY (COD_ATOR) REFERENCES ATOR(ID_ATOR),
    CONSTRAINT PARTICIPA_fk2 FOREIGN KEY (COD_FILME) REFERENCES FILME(ID_FILME),
);
commit;

CREATE TABLE DIRETOR(
	ID_DIRETOR VARCHAR(20 BYTE),
	NOME_DIRETOR VARCHAR(40 BYTE),
	COD_ESTUDIO VARCHAR(20 BYTE),

	CONSTRAINT DIRETOR_pk PRIMARY KEY (ID_DIRETOR),
    CONSTRAINT DIRETOR_fk FOREIGN KEY (COD_ESTUDIO) REFERENCES ESTUDIO(ID_ESTUDIO),

);
commit;

CREATE TABLE ESTUDIO(
	ID_ESTUDIO VARCHAR(20 BYTE),
	NOME_ESTUDIO VARCHAR(40 BYTE),

	CONSTRAINT DIRETOR_pk PRIMARY KEY (ID_ESTUDIO),

);
commit;